<?php

declare(strict_types=1);

use Phinx\Seed\AbstractSeed;

final class CitiesSeeder extends AbstractSeed
{
    public function run(): void
    {
        $cities = [
            ['name' => 'Birmingham',       'state' => 'AL'],
            ['name' => 'Huntsville',        'state' => 'AL'],
            ['name' => 'Mobile',            'state' => 'AL'],
            ['name' => 'Montgomery',        'state' => 'AL'],
            ['name' => 'Anchorage',         'state' => 'AK'],
            ['name' => 'Chandler',          'state' => 'AZ'],
            ['name' => 'Gilbert',           'state' => 'AZ'],
            ['name' => 'Glendale',          'state' => 'AZ'],
            ['name' => 'Mesa',              'state' => 'AZ'],
            ['name' => 'Peoria',            'state' => 'AZ'],
            ['name' => 'Phoenix',           'state' => 'AZ'],
            ['name' => 'Scottsdale',        'state' => 'AZ'],
            ['name' => 'Surprise',          'state' => 'AZ'],
            ['name' => 'Tempe',             'state' => 'AZ'],
            ['name' => 'Tucson',            'state' => 'AZ'],
            ['name' => 'Fayetteville',      'state' => 'AR'],
            ['name' => 'Fort Smith',        'state' => 'AR'],
            ['name' => 'Little Rock',       'state' => 'AR'],
            ['name' => 'Anaheim',           'state' => 'CA'],
            ['name' => 'Antioch',           'state' => 'CA'],
            ['name' => 'Bakersfield',       'state' => 'CA'],
            ['name' => 'Berkeley',          'state' => 'CA'],
            ['name' => 'Chula Vista',       'state' => 'CA'],
            ['name' => 'Clovis',            'state' => 'CA'],
            ['name' => 'Concord',           'state' => 'CA'],
            ['name' => 'Corona',            'state' => 'CA'],
            ['name' => 'Costa Mesa',        'state' => 'CA'],
            ['name' => 'Downey',            'state' => 'CA'],
            ['name' => 'El Monte',          'state' => 'CA'],
            ['name' => 'Elk Grove',         'state' => 'CA'],
            ['name' => 'Escondido',         'state' => 'CA'],
            ['name' => 'Fontana',           'state' => 'CA'],
            ['name' => 'Fremont',           'state' => 'CA'],
            ['name' => 'Fresno',            'state' => 'CA'],
            ['name' => 'Fullerton',         'state' => 'CA'],
            ['name' => 'Garden Grove',      'state' => 'CA'],
            ['name' => 'Glendale',          'state' => 'CA'],
            ['name' => 'Hayward',           'state' => 'CA'],
            ['name' => 'Huntington Beach',  'state' => 'CA'],
            ['name' => 'Inglewood',         'state' => 'CA'],
            ['name' => 'Irvine',            'state' => 'CA'],
            ['name' => 'Lancaster',         'state' => 'CA'],
            ['name' => 'Long Beach',        'state' => 'CA'],
            ['name' => 'Los Angeles',       'state' => 'CA'],
            ['name' => 'Modesto',           'state' => 'CA'],
            ['name' => 'Moreno Valley',     'state' => 'CA'],
            ['name' => 'Norwalk',           'state' => 'CA'],
            ['name' => 'Oakland',           'state' => 'CA'],
            ['name' => 'Oceanside',         'state' => 'CA'],
            ['name' => 'Ontario',           'state' => 'CA'],
            ['name' => 'Orange',            'state' => 'CA'],
            ['name' => 'Oxnard',            'state' => 'CA'],
            ['name' => 'Palmdale',          'state' => 'CA'],
            ['name' => 'Pasadena',          'state' => 'CA'],
            ['name' => 'Pomona',            'state' => 'CA'],
            ['name' => 'Rancho Cucamonga',  'state' => 'CA'],
            ['name' => 'Riverside',         'state' => 'CA'],
            ['name' => 'Roseville',         'state' => 'CA'],
            ['name' => 'Sacramento',        'state' => 'CA'],
            ['name' => 'Salinas',           'state' => 'CA'],
            ['name' => 'San Bernardino',    'state' => 'CA'],
            ['name' => 'San Diego',         'state' => 'CA'],
            ['name' => 'San Francisco',     'state' => 'CA'],
            ['name' => 'San Jose',          'state' => 'CA'],
            ['name' => 'Santa Ana',         'state' => 'CA'],
            ['name' => 'Santa Clara',       'state' => 'CA'],
            ['name' => 'Santa Clarita',     'state' => 'CA'],
            ['name' => 'Santa Rosa',        'state' => 'CA'],
            ['name' => 'Simi Valley',       'state' => 'CA'],
            ['name' => 'Stockton',          'state' => 'CA'],
            ['name' => 'Sunnyvale',         'state' => 'CA'],
            ['name' => 'Thousand Oaks',     'state' => 'CA'],
            ['name' => 'Torrance',          'state' => 'CA'],
            ['name' => 'Visalia',           'state' => 'CA'],
            ['name' => 'Arvada',            'state' => 'CO'],
            ['name' => 'Aurora',            'state' => 'CO'],
            ['name' => 'Centennial',        'state' => 'CO'],
            ['name' => 'Colorado Springs',  'state' => 'CO'],
            ['name' => 'Denver',            'state' => 'CO'],
            ['name' => 'Fort Collins',      'state' => 'CO'],
            ['name' => 'Lakewood',          'state' => 'CO'],
            ['name' => 'Pueblo',            'state' => 'CO'],
            ['name' => 'Thornton',          'state' => 'CO'],
            ['name' => 'Westminster',       'state' => 'CO'],
            ['name' => 'Bridgeport',        'state' => 'CT'],
            ['name' => 'Hartford',          'state' => 'CT'],
            ['name' => 'New Haven',         'state' => 'CT'],
            ['name' => 'Stamford',          'state' => 'CT'],
            ['name' => 'Waterbury',         'state' => 'CT'],
            ['name' => 'Washington',        'state' => 'DC'],
            ['name' => 'Cape Coral',        'state' => 'FL'],
            ['name' => 'Clearwater',        'state' => 'FL'],
            ['name' => 'Coral Springs',     'state' => 'FL'],
            ['name' => 'Fort Lauderdale',   'state' => 'FL'],
            ['name' => 'Gainesville',       'state' => 'FL'],
            ['name' => 'Hialeah',           'state' => 'FL'],
            ['name' => 'Hollywood',         'state' => 'FL'],
            ['name' => 'Jacksonville',      'state' => 'FL'],
            ['name' => 'Lakeland',          'state' => 'FL'],
            ['name' => 'Miami',             'state' => 'FL'],
            ['name' => 'Miramar',           'state' => 'FL'],
            ['name' => 'Orlando',           'state' => 'FL'],
            ['name' => 'Palm Bay',          'state' => 'FL'],
            ['name' => 'Pembroke Pines',    'state' => 'FL'],
            ['name' => 'Pompano Beach',     'state' => 'FL'],
            ['name' => 'Port St. Lucie',    'state' => 'FL'],
            ['name' => 'St. Petersburg',    'state' => 'FL'],
            ['name' => 'Tallahassee',       'state' => 'FL'],
            ['name' => 'Tampa',             'state' => 'FL'],
            ['name' => 'West Palm Beach',   'state' => 'FL'],
            ['name' => 'Albany',            'state' => 'GA'],
            ['name' => 'Athens',            'state' => 'GA'],
            ['name' => 'Atlanta',           'state' => 'GA'],
            ['name' => 'Augusta',           'state' => 'GA'],
            ['name' => 'Columbus',          'state' => 'GA'],
            ['name' => 'Macon',             'state' => 'GA'],
            ['name' => 'Roswell',           'state' => 'GA'],
            ['name' => 'Sandy Springs',     'state' => 'GA'],
            ['name' => 'Savannah',          'state' => 'GA'],
            ['name' => 'Honolulu',          'state' => 'HI'],
            ['name' => 'Boise',             'state' => 'ID'],
            ['name' => 'Meridian',          'state' => 'ID'],
            ['name' => 'Nampa',             'state' => 'ID'],
            ['name' => 'Aurora',            'state' => 'IL'],
            ['name' => 'Chicago',           'state' => 'IL'],
            ['name' => 'Elgin',             'state' => 'IL'],
            ['name' => 'Joliet',            'state' => 'IL'],
            ['name' => 'Naperville',        'state' => 'IL'],
            ['name' => 'Peoria',            'state' => 'IL'],
            ['name' => 'Rockford',          'state' => 'IL'],
            ['name' => 'Springfield',       'state' => 'IL'],
            ['name' => 'Waukegan',          'state' => 'IL'],
            ['name' => 'Bloomington',       'state' => 'IN'],
            ['name' => 'Carmel',            'state' => 'IN'],
            ['name' => 'Evansville',        'state' => 'IN'],
            ['name' => 'Fishers',           'state' => 'IN'],
            ['name' => 'Fort Wayne',        'state' => 'IN'],
            ['name' => 'Indianapolis',      'state' => 'IN'],
            ['name' => 'South Bend',        'state' => 'IN'],
            ['name' => 'Cedar Rapids',      'state' => 'IA'],
            ['name' => 'Davenport',         'state' => 'IA'],
            ['name' => 'Des Moines',        'state' => 'IA'],
            ['name' => 'Sioux City',        'state' => 'IA'],
            ['name' => 'Kansas City',       'state' => 'KS'],
            ['name' => 'Olathe',            'state' => 'KS'],
            ['name' => 'Overland Park',     'state' => 'KS'],
            ['name' => 'Topeka',            'state' => 'KS'],
            ['name' => 'Wichita',           'state' => 'KS'],
            ['name' => 'Bowling Green',     'state' => 'KY'],
            ['name' => 'Lexington',         'state' => 'KY'],
            ['name' => 'Louisville',        'state' => 'KY'],
            ['name' => 'Baton Rouge',       'state' => 'LA'],
            ['name' => 'Lafayette',         'state' => 'LA'],
            ['name' => 'Metairie',          'state' => 'LA'],
            ['name' => 'New Orleans',       'state' => 'LA'],
            ['name' => 'Shreveport',        'state' => 'LA'],
            ['name' => 'Baltimore',         'state' => 'MD'],
            ['name' => 'Frederick',         'state' => 'MD'],
            ['name' => 'Rockville',         'state' => 'MD'],
            ['name' => 'Boston',            'state' => 'MA'],
            ['name' => 'Cambridge',         'state' => 'MA'],
            ['name' => 'Lowell',            'state' => 'MA'],
            ['name' => 'Springfield',       'state' => 'MA'],
            ['name' => 'Worcester',         'state' => 'MA'],
            ['name' => 'Ann Arbor',         'state' => 'MI'],
            ['name' => 'Clinton Township',  'state' => 'MI'],
            ['name' => 'Dearborn',          'state' => 'MI'],
            ['name' => 'Detroit',           'state' => 'MI'],
            ['name' => 'Flint',             'state' => 'MI'],
            ['name' => 'Grand Rapids',      'state' => 'MI'],
            ['name' => 'Lansing',           'state' => 'MI'],
            ['name' => 'Livonia',           'state' => 'MI'],
            ['name' => 'Sterling Heights',  'state' => 'MI'],
            ['name' => 'Warren',            'state' => 'MI'],
            ['name' => 'Bloomington',       'state' => 'MN'],
            ['name' => 'Duluth',            'state' => 'MN'],
            ['name' => 'Minneapolis',       'state' => 'MN'],
            ['name' => 'Rochester',         'state' => 'MN'],
            ['name' => 'St. Paul',          'state' => 'MN'],
            ['name' => 'Gulfport',          'state' => 'MS'],
            ['name' => 'Jackson',           'state' => 'MS'],
            ['name' => 'Columbia',          'state' => 'MO'],
            ['name' => 'Independence',      'state' => 'MO'],
            ['name' => 'Kansas City',       'state' => 'MO'],
            ['name' => 'Springfield',       'state' => 'MO'],
            ['name' => 'St. Louis',         'state' => 'MO'],
            ['name' => 'Bellevue',          'state' => 'NE'],
            ['name' => 'Lincoln',           'state' => 'NE'],
            ['name' => 'Omaha',             'state' => 'NE'],
            ['name' => 'Henderson',         'state' => 'NV'],
            ['name' => 'Las Vegas',         'state' => 'NV'],
            ['name' => 'North Las Vegas',   'state' => 'NV'],
            ['name' => 'Reno',              'state' => 'NV'],
            ['name' => 'Sparks',            'state' => 'NV'],
            ['name' => 'Manchester',        'state' => 'NH'],
            ['name' => 'Nashua',            'state' => 'NH'],
            ['name' => 'Camden',            'state' => 'NJ'],
            ['name' => 'Clifton',           'state' => 'NJ'],
            ['name' => 'Edison',            'state' => 'NJ'],
            ['name' => 'Elizabeth',         'state' => 'NJ'],
            ['name' => 'Jersey City',       'state' => 'NJ'],
            ['name' => 'Newark',            'state' => 'NJ'],
            ['name' => 'Paterson',          'state' => 'NJ'],
            ['name' => 'Trenton',           'state' => 'NJ'],
            ['name' => 'Albuquerque',       'state' => 'NM'],
            ['name' => 'Las Cruces',        'state' => 'NM'],
            ['name' => 'Rio Rancho',        'state' => 'NM'],
            ['name' => 'Albany',            'state' => 'NY'],
            ['name' => 'Buffalo',           'state' => 'NY'],
            ['name' => 'New York',          'state' => 'NY'],
            ['name' => 'Rochester',         'state' => 'NY'],
            ['name' => 'Syracuse',          'state' => 'NY'],
            ['name' => 'Yonkers',           'state' => 'NY'],
            ['name' => 'Cary',              'state' => 'NC'],
            ['name' => 'Charlotte',         'state' => 'NC'],
            ['name' => 'Concord',           'state' => 'NC'],
            ['name' => 'Durham',            'state' => 'NC'],
            ['name' => 'Fayetteville',      'state' => 'NC'],
            ['name' => 'Greensboro',        'state' => 'NC'],
            ['name' => 'High Point',        'state' => 'NC'],
            ['name' => 'Raleigh',           'state' => 'NC'],
            ['name' => 'Wilmington',        'state' => 'NC'],
            ['name' => 'Winston-Salem',     'state' => 'NC'],
            ['name' => 'Bismarck',          'state' => 'ND'],
            ['name' => 'Fargo',             'state' => 'ND'],
            ['name' => 'Akron',             'state' => 'OH'],
            ['name' => 'Canton',            'state' => 'OH'],
            ['name' => 'Cincinnati',        'state' => 'OH'],
            ['name' => 'Cleveland',         'state' => 'OH'],
            ['name' => 'Columbus',          'state' => 'OH'],
            ['name' => 'Dayton',            'state' => 'OH'],
            ['name' => 'Parma',             'state' => 'OH'],
            ['name' => 'Toledo',            'state' => 'OH'],
            ['name' => 'Broken Arrow',      'state' => 'OK'],
            ['name' => 'Lawton',            'state' => 'OK'],
            ['name' => 'Norman',            'state' => 'OK'],
            ['name' => 'Oklahoma City',     'state' => 'OK'],
            ['name' => 'Tulsa',             'state' => 'OK'],
            ['name' => 'Bend',              'state' => 'OR'],
            ['name' => 'Eugene',            'state' => 'OR'],
            ['name' => 'Gresham',           'state' => 'OR'],
            ['name' => 'Hillsboro',         'state' => 'OR'],
            ['name' => 'Medford',           'state' => 'OR'],
            ['name' => 'Portland',          'state' => 'OR'],
            ['name' => 'Salem',             'state' => 'OR'],
            ['name' => 'Allentown',         'state' => 'PA'],
            ['name' => 'Erie',              'state' => 'PA'],
            ['name' => 'Philadelphia',      'state' => 'PA'],
            ['name' => 'Pittsburgh',        'state' => 'PA'],
            ['name' => 'Reading',           'state' => 'PA'],
            ['name' => 'Scranton',          'state' => 'PA'],
            ['name' => 'Cranston',          'state' => 'RI'],
            ['name' => 'Providence',        'state' => 'RI'],
            ['name' => 'Warwick',           'state' => 'RI'],
            ['name' => 'Charleston',        'state' => 'SC'],
            ['name' => 'Columbia',          'state' => 'SC'],
            ['name' => 'Mount Pleasant',    'state' => 'SC'],
            ['name' => 'North Charleston',  'state' => 'SC'],
            ['name' => 'Rock Hill',         'state' => 'SC'],
            ['name' => 'Rapid City',        'state' => 'SD'],
            ['name' => 'Sioux Falls',       'state' => 'SD'],
            ['name' => 'Chattanooga',       'state' => 'TN'],
            ['name' => 'Clarksville',       'state' => 'TN'],
            ['name' => 'Franklin',          'state' => 'TN'],
            ['name' => 'Jackson',           'state' => 'TN'],
            ['name' => 'Knoxville',         'state' => 'TN'],
            ['name' => 'Memphis',           'state' => 'TN'],
            ['name' => 'Murfreesboro',      'state' => 'TN'],
            ['name' => 'Nashville',         'state' => 'TN'],
            ['name' => 'Abilene',           'state' => 'TX'],
            ['name' => 'Amarillo',          'state' => 'TX'],
            ['name' => 'Arlington',         'state' => 'TX'],
            ['name' => 'Austin',            'state' => 'TX'],
            ['name' => 'Beaumont',          'state' => 'TX'],
            ['name' => 'Brownsville',       'state' => 'TX'],
            ['name' => 'Carrollton',        'state' => 'TX'],
            ['name' => 'Corpus Christi',    'state' => 'TX'],
            ['name' => 'Dallas',            'state' => 'TX'],
            ['name' => 'Denton',            'state' => 'TX'],
            ['name' => 'El Paso',           'state' => 'TX'],
            ['name' => 'Fort Worth',        'state' => 'TX'],
            ['name' => 'Frisco',            'state' => 'TX'],
            ['name' => 'Garland',           'state' => 'TX'],
            ['name' => 'Grand Prairie',     'state' => 'TX'],
            ['name' => 'Houston',           'state' => 'TX'],
            ['name' => 'Irving',            'state' => 'TX'],
            ['name' => 'Killeen',           'state' => 'TX'],
            ['name' => 'Laredo',            'state' => 'TX'],
            ['name' => 'Lewisville',        'state' => 'TX'],
            ['name' => 'Lubbock',           'state' => 'TX'],
            ['name' => 'McAllen',           'state' => 'TX'],
            ['name' => 'McKinney',          'state' => 'TX'],
            ['name' => 'Mesquite',          'state' => 'TX'],
            ['name' => 'Midland',           'state' => 'TX'],
            ['name' => 'Odessa',            'state' => 'TX'],
            ['name' => 'Pasadena',          'state' => 'TX'],
            ['name' => 'Pearland',          'state' => 'TX'],
            ['name' => 'Plano',             'state' => 'TX'],
            ['name' => 'Richardson',        'state' => 'TX'],
            ['name' => 'Round Rock',        'state' => 'TX'],
            ['name' => 'San Antonio',       'state' => 'TX'],
            ['name' => 'Waco',              'state' => 'TX'],
            ['name' => 'Layton',            'state' => 'UT'],
            ['name' => 'Orem',              'state' => 'UT'],
            ['name' => 'Provo',             'state' => 'UT'],
            ['name' => 'Salt Lake City',    'state' => 'UT'],
            ['name' => 'Sandy',             'state' => 'UT'],
            ['name' => 'St. George',        'state' => 'UT'],
            ['name' => 'West Jordan',       'state' => 'UT'],
            ['name' => 'West Valley City',  'state' => 'UT'],
            ['name' => 'Alexandria',        'state' => 'VA'],
            ['name' => 'Chesapeake',        'state' => 'VA'],
            ['name' => 'Fredericksburg',    'state' => 'VA'],
            ['name' => 'Hampton',           'state' => 'VA'],
            ['name' => 'Newport News',      'state' => 'VA'],
            ['name' => 'Norfolk',           'state' => 'VA'],
            ['name' => 'Richmond',          'state' => 'VA'],
            ['name' => 'Roanoke',           'state' => 'VA'],
            ['name' => 'Virginia Beach',    'state' => 'VA'],
            ['name' => 'Bellingham',        'state' => 'WA'],
            ['name' => 'Bellevue',          'state' => 'WA'],
            ['name' => 'Everett',           'state' => 'WA'],
            ['name' => 'Kent',              'state' => 'WA'],
            ['name' => 'Kirkland',          'state' => 'WA'],
            ['name' => 'Renton',            'state' => 'WA'],
            ['name' => 'Seattle',           'state' => 'WA'],
            ['name' => 'Spokane',           'state' => 'WA'],
            ['name' => 'Spokane Valley',    'state' => 'WA'],
            ['name' => 'Tacoma',            'state' => 'WA'],
            ['name' => 'Vancouver',         'state' => 'WA'],
            ['name' => 'Charleston',        'state' => 'WV'],
            ['name' => 'Huntington',        'state' => 'WV'],
            ['name' => 'Appleton',          'state' => 'WI'],
            ['name' => 'Green Bay',         'state' => 'WI'],
            ['name' => 'Kenosha',           'state' => 'WI'],
            ['name' => 'Madison',           'state' => 'WI'],
            ['name' => 'Milwaukee',         'state' => 'WI'],
            ['name' => 'Racine',            'state' => 'WI'],
            ['name' => 'Waukesha',          'state' => 'WI'],
            ['name' => 'Casper',            'state' => 'WY'],
            ['name' => 'Cheyenne',          'state' => 'WY'],
        ];

        $table = $this->table('cities');
        $table->insert($cities)->saveData();
    }
}
